function [J, MSD, E] = determine_cost(Kp, Ki, Kd, N, m, x_thrust, x_cg, F_static, mu_k)
profile = 2;

sim_input = Simulink.SimulationInput('controller');
sim_input = sim_input.setVariable('Kp', Kp) ...
    .setVariable('Ki', Ki) ...
    .setVariable('Kd', Kd) ...
    .setVariable('N', N) ...
    .setVariable('m_structure', m) ...
    .setVariable('x_thrust', x_thrust) ...
    .setVariable('x_cg', x_cg) ...
    .setVariable('F_static', F_static) ...
    .setVariable('mu_k', mu_k) ...
    .setVariable('profile', profile);

sim_output = sim(sim_input);

MSD_manual = 0.002926; % Manually tuned MSD
E_manual = 10.78; % Manually tuned energy

MSD_arr = sim_output.MSD.Data;
E_arr = sim_output.energy.Data;

MSD = MSD_arr(end);
E = E_arr(end);

J = (3/7) * (E / E_manual) + (4/7) * (MSD / MSD_manual);
end